apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sashamihalache/git-tix-auth
          env:
            - name: JWT_KEY # name i will use in nodejs
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # key object  stored in kubectl
                  key: JWT_KEY # actualy key from the key object which has value asdf
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
