apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: sashamihalache/git-tix-tickets
          env:
            - name: JWT_KEY # name i will use in nodejs
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # key object  stored in kubectl
                  key: JWT_KEY # actualy key from the key object which has value asdf
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
